### ISSUE TITLE
QUESTION Can I override internal dependencies?

### ISSUE THREAD

**Issue by sdrygalski** [sockeqwe/mosby-conductor#1]
README states that

> Internal dependencies are Conductor 1.1.4 and Mosby 2.0.1

Can I simply override them in gradle by using:

> compile 'com.bluelinelabs:conductor:1.1.6'
> compile 'com.bluelinelabs:conductor-rxlifecycle:1.1.6'

?

**Comment by sockeqwe** [comment]
Yes, this is safe to do!
However,  there is an issues with Conductor #2
