### ISSUE TITLE
Add support for Mosby 3.0 and MVI

### ISSUE THREAD

**Issue by mheras** [sockeqwe/mosby-conductor#12]
Hi Hannes,

I know Mosby 3 is still under development, but it would be great to have your mosby-conductor plugin with MVI support. Is this something you are planning for the near future?

Thanks!

**Comment by sockeqwe** [comment]
Its on my to-do list. I do have plans to dinish Mosby 3 in February and have planed to work on conductor plugin afterwards. Since it should be pretty straight forward, I think I could create a early beta version during this weekend if it is critical for you

**Comment by mheras** [comment]
Actually, it's not critical, but I want to take the idea of integrating Conductor and MVI to my work, and since you are currently working on adding this functionality to Mosby, I think it would be better to use it as part of the stack instead of making my own version of it. But I can definitely wait until Mosby 3 is finished!

Thank you Hannes, you are contributing a lot to the Android community :)

**Comment by markus2610** [comment]
I have started with it. It works so far. 

[link to my fork](https://github.com/markus2610/mosby-conductor)

**Comment by sockeqwe** [comment]
Funny, I have also started to work on that. I took a look at your code and found out that there are some parts that could be optimized for conductor. 

Should we merge our code together? Although, I'm almost done with my implementation

**Comment by markus2610** [comment]
We can merge. How far are you? Optimized for conductor is good 👍

**Comment by sockeqwe** [comment]
basically just the `MviController` is missing and a concrete example ...
Please send me a pull request and I will work on that in the next hour...

**Comment by sockeqwe** [comment]
Ok, I have released a first alpha version
```gradle
compile 'com.hannesdorfmann.mosby3:mvi-conductor:3.0.0-alhpa1'
```

Please note that the group id and package name has been changed to com.hannesdorfmann.mosby**3**.
You may have to change your imports in your source code (You can use find / replace in path).

Thanks for your help @markus2610
