### ISSUE TITLE
Dependency not found

### ISSUE THREAD

**Issue by markus2610** [sockeqwe/mosby-conductor#14]
Error:Failed to resolve: com.hannesdorfmann.mosby3:mvi-conductor:3.0.0-alhpa1

**Comment by sockeqwe** [comment]
https://search.maven.org/#artifactdetails%7Ccom.hannesdorfmann.mosby3%7Cmvi-conductor%7C3.0.0-alpha1%7Caar

Maybe it just took some time until it was synced with repo

**Comment by sockeqwe** [comment]
oops there was a typo in `alpha1`

**Comment by markus2610** [comment]
Thanks
