### ISSUE TITLE
MvpLceViewStateController does not save data.

### ISSUE THREAD

**Issue by pavel163** [sockeqwe/mosby-conductor#15]
I use MvpLceViewStateController. After the coup of the screen is called again method loadData(pullToRefresh: Boolean)

**Comment by sockeqwe** [comment]
can you give some more details? When does this happens, under which condition? are you navigating through different screens? What does "does not save data" mean?
Which version are you using?

**Comment by pavel163** [comment]
I use 0.8.2 version. How to make a save state controller? I use `MvpLceViewStateController `. Now I turn screen and always run loadData

[My controller](https://github.com/pavel163/DevelopersLife/blob/master/app/src/main/kotlin/com/ebr163/developerslife/controller/gif/GifsController.kt)

**Comment by sockeqwe** [comment]
This is not an mosby conductor issue.
For some reason an entirely new GifController instance is instantiated
every time you rotate your screen.

Please check your code. I guess it is a combination of
RouterPagerController and BottomNavigationView (check if the
bottomnavigation listener fires after screen orientation changes becaue it
restores its state) that accidentally causes to create a new GifController
instance.

If you really think this is a bug then please report it at conductor github
issue tracker.

Bakht Ergashev <notifications@github.com> schrieb am Sa., 4. Feb. 2017,
21:35:
