### ISSUE TITLE
[Duplicate] unable to recreate the state of force stopped application

### ISSUE THREAD

**Issue by Kyba1985** [sockeqwe/mosby-conductor#22]
Mosby Version:
compile 'com.hannesdorfmann.mosby:viewstate-conductor:0.8.2'
Expected behavior
the controller that are added to router are recreated
Actual behavior (include a stacktrace if crash)
the saveinstancestate of the application is null when recover from force stopped application and the application reset to first controller, all the backstack is lost.
Steps to reproduce the behavior or link to a sample repository
From the root controller, go to a viewpager controller , than go to a child controller of folder details and than to another deeper controller of inner folder. when i go back to home and force kill the application from android studio, when i select the application from list of apps, the backstack is lost and the app restart from the first controller, and the saveinstancestate is null.

The demo app of conductor without mosby works well, the backstack is recreated and the saveinstancestate is not null when recreate the app state. So i'm thinking that the problem is from mosby.

Do you have any clue about this strange behavior?

**Comment by sockeqwe** [comment]
Duplicate: https://github.com/sockeqwe/mosby/issues/227

Please post the issue either here (prefer this repository since it is a mosby-conductor thing) or on the other repo, but not both.
