### ISSUE TITLE
'unbindIntents' not called if controller is destroyed while view is detached

### ISSUE THREAD

**Issue by fullkomnun** [sockeqwe/mosby-conductor#32]
According to the documentation it seems that 'unbindIntents' is supposed to be called when the view detaches from the presenter for the last time and is meant to be destroyed and therefore could be used for presenter "cleanup".

However, if the controller is being destroyed while on the backstack(not the top controller), such as when calling Router::popToRoot from the top controller, then the controller is destroyed but since view is already detached 'unbindIntents' is never called prior to this presenter being "destroyed".

**Comment by sockeqwe** [comment]
Thanks for reporting.
This is a known issue and will be fixed soon (next week) with the release
of Mosby 3.1.0 which adds internally better support for onStop() and
onDestroy() which is exactly the problem here.
Stay tuned.

Or Noyman <notifications@github.com> schrieb am Sa., 11. Nov. 2017, 08:14:

**Comment by fullkomnun** [comment]
Is there any recommended workaround in the meanwhile or ETA for the 3.1.0 release?

**Comment by sockeqwe** [comment]
Im on holidays since last week and will return next Monday. Mosby 3.1.0 has
highest prio then, so you can expect a fix / release on Tuesday.

Workaround: you can check the MVI lifecycle listener implementation and use
that one. In onDestroy() add presenter.detachView(false)

Or Noyman <notifications@github.com> schrieb am Di., 21. Nov. 2017, 15:22:

**Comment by fullkomnun** [comment]
Yeah, that's what I did and it's working fine for us.
Enjoy your vacation =]

**Comment by sockeqwe** [comment]
This is fixed now. Release, synced and available in a few hours.
