### ISSUE TITLE
Code Sample in JAVA?

### ISSUE THREAD

**Issue by sirvon** [sockeqwe/mosby-conductor#6]
Thanks for the lib!

Is there a code sample on how to implement mosby with conductor in java?

**Comment by sockeqwe** [comment]
Not yet ...

@sirvonthomas notifications@github.com schrieb am Mo., 8. Aug. 2016,
10:27:

**Comment by sockeqwe** [comment]
But you can have a look at code samples from Mosby repository. There are
plenty written in java, and there is no difference between using i.e. a
fragment or conductor controller. Mosby offers the same api for both

Hannes Dorfmann hannes.dorfmann@gmail.com schrieb am Mo., 8. Aug. 2016,
16:47:

**Comment by sirvon** [comment]
and that said it all...a fragment is equivalent to a conductor controller! thanks!
