### ISSUE TITLE
No Conductor(Bundle) constructor

### ISSUE THREAD

**Issue by dimsuz** [sockeqwe/mosby-conductor#7]
I needed to pass some Bundle wtih arguments to `MvpController` and found out that I can't do that, because mosby's version implements only a default constructor with no arguments, making it impossible to pass any of them to the Conductor library.

Is this an explicit design choice or you simply didn't do it yet?

**Comment by sockeqwe** [comment]
My bad, I simply forgot about constructors. 

I have fixed that and released a new version`0.8.3` ... Should be available soon via maven central (or specify oss sontype url directly to get it sooner).

Thanks for reporting!

**Comment by dimsuz** [comment]
That was quick! I didn't even come close to creating a PR based on your answer :) Thanks! Having a new version also helps: I will remove a workaround I had to put today.
