### ISSUE TITLE
attachView() is not getting called after launch with locked orientation

### ISSUE THREAD

**Issue by dimsuz** [sockeqwe/mosby-conductor#8]
I'm using a usual stuff in `Activity.onCreate()`:

``` kotlin
  override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)

    val container = findViewById(R.id.controller_content) as ViewGroup
    conductorRouter = Conductor.attachRouter(this, container, savedInstanceState)
    Timber.e("onCreate, has root controller: ${conductorRouter.hasRootController()}")
    requestedOrientation = ActivityInfo.SCREEN_ORIENTATION_PORTRAIT
    if (!conductorRouter.hasRootController()) {
      conductorRouter.setRoot(RouterTransaction.with(MyController()))
    }
  }
```

Steps to reproduce:
1. Call `setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_PORTRAIT)` in `Activity.onCreate()`
2. Rotate your device into a landscape mode **prior** to launching
3. Launch application
4. It launches rotated in portrait, as requested, but visually there's no controller inside

And here's why.
The following sequence of calls was observed in logs

```
-- launch in landscape --
MyController  D  createPresenter
   Presenter  D  attachView
-- rotated to portrait by system --
   Presenter  D  detachView retainInstance=true
MainActivity  D  onCreate, has root controller: true
```

And nothing after this...
That is: it seems that the first round of `attach/detach` was happening in the landscape mode, but then activity immediately was rotated by the system into a requested orientation - and here another `onCreate` happened - and that one **was not** followed by `attach/detach`

If I remove locked orientation stuff than everything goes smoothly:

```
-- launch in landscape --
MainActivity  D  onCreate, has root controller: false 
MyController  D  onCreateView
MyController  D  createPresenter
   Presenter  D  attachView
-- rotated to portrait by hand --
   Presenter  D  detachView true
MainActivity  D  onCreate, has root controller: true
MyController  D  onCreateView
   Presenter  D  attachView
```

I'm not sure if this is a bug or me doing something wrong, and if this **is** a bug, I'm not sure if it's mosby-conductor one or Conductor one or even an Android one :)

**Comment by dimsuz** [comment]
I will try to look into this a bit further, but currently have a deadline approaching, kind of busy - decided to report in case you'll be interested or have time to investigate :) Or maybe you already know this kind of problem...

**Comment by sockeqwe** [comment]
Thanks for reporting, I will take a look next week

**Comment by EricKuck** [comment]
I just came across this issue and wasn't able to reproduce at all. I'm pretty sure it was fixed in Conductor a few versions ago.

**Comment by dimsuz** [comment]
Great! I will give it a try, but I think I haven't seen it recently too. 
I forgot to mention that this was reproduced with `conductor-2.0.1`, now I am using `2.0.3`, so I guess if this library has its dependencies updated this issue can be closed too.

**Comment by sockeqwe** [comment]
thanks @EricKuck  for your feedback! I will close this for now.
